before_build:
  - cd CafeUnEuro
  - nuget restore

nuget:
  project_feed: true

build:
  parallel: true                  # enable MSBuild parallel builds
  project: CafeUnEuro\CafeUnEuro.sln         # path to Visual Studio solution or project
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
